global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'prometheus:9090' ]

- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]

- job_name: 'backend-api'
  static_configs:
  - targets: [ 'backend:3000' ]
  metrics_path: '/metrics'
  scrape_interval: 10s

- job_name: 'mongodb-exporter'
  static_configs:
  - targets: [ 'mongodb-exporter:9216' ]
  scrape_interval: 15s
