apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/your-org/mern-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: MONGO_URI
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20

