apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mern-monitoring
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017

