apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <dockerhub-username>/mern-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/mernmonitor
